//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnpactoCA.WSTarjeta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSTarjeta.WSTarjetaSoap")]
    public interface WSTarjetaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/testService", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string testService(string sec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/testService", ReplyAction="*")]
        System.Threading.Tasks.Task<string> testServiceAsync(string sec);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatosClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DatosClientes(int ptipo_convenio, string sec, string rutayarchivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DatosClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<string> DatosClientesAsync(int ptipo_convenio, string sec, string rutayarchivo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArchivoClientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        EnpactoCA.WSTarjeta.ArchivoClientesResponse ArchivoClientes(EnpactoCA.WSTarjeta.ArchivoClientesRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ArchivoClientes", ReplyAction="*")]
        System.Threading.Tasks.Task<EnpactoCA.WSTarjeta.ArchivoClientesResponse> ArchivoClientesAsync(EnpactoCA.WSTarjeta.ArchivoClientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarMovimientos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MarshalByRefObject))]
        EnpactoCA.WSTarjeta.CargarMovimientosResponse CargarMovimientos(EnpactoCA.WSTarjeta.CargarMovimientosRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CargarMovimientos", ReplyAction="*")]
        System.Threading.Tasks.Task<EnpactoCA.WSTarjeta.CargarMovimientosResponse> CargarMovimientosAsync(EnpactoCA.WSTarjeta.CargarMovimientosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class StreamReader : TextReader {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StreamReader))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class TextReader : MarshalByRefObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextReader))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StreamReader))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class MarshalByRefObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ArchivoClientes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ArchivoClientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ptipo_convenio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sec;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string rutayarchivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string perror;
        
        public ArchivoClientesRequest() {
        }
        
        public ArchivoClientesRequest(int ptipo_convenio, string sec, string rutayarchivo, string perror) {
            this.ptipo_convenio = ptipo_convenio;
            this.sec = sec;
            this.rutayarchivo = rutayarchivo;
            this.perror = perror;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ArchivoClientesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ArchivoClientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public EnpactoCA.WSTarjeta.StreamReader ArchivoClientesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string perror;
        
        public ArchivoClientesResponse() {
        }
        
        public ArchivoClientesResponse(EnpactoCA.WSTarjeta.StreamReader ArchivoClientesResult, string perror) {
            this.ArchivoClientesResult = ArchivoClientesResult;
            this.perror = perror;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarMovimientos", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarMovimientosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int ptipo_convenio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string sec;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string[] data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.DateTime fecha;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string perror;
        
        public CargarMovimientosRequest() {
        }
        
        public CargarMovimientosRequest(int ptipo_convenio, string sec, string[] data, System.DateTime fecha, string perror) {
            this.ptipo_convenio = ptipo_convenio;
            this.sec = sec;
            this.data = data;
            this.fecha = fecha;
            this.perror = perror;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CargarMovimientosResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CargarMovimientosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public long CargarMovimientosResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string perror;
        
        public CargarMovimientosResponse() {
        }
        
        public CargarMovimientosResponse(long CargarMovimientosResult, string perror) {
            this.CargarMovimientosResult = CargarMovimientosResult;
            this.perror = perror;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSTarjetaSoapChannel : EnpactoCA.WSTarjeta.WSTarjetaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSTarjetaSoapClient : System.ServiceModel.ClientBase<EnpactoCA.WSTarjeta.WSTarjetaSoap>, EnpactoCA.WSTarjeta.WSTarjetaSoap {
        
        public WSTarjetaSoapClient() {
        }
        
        public WSTarjetaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSTarjetaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTarjetaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSTarjetaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string testService(string sec) {
            return base.Channel.testService(sec);
        }
        
        public System.Threading.Tasks.Task<string> testServiceAsync(string sec) {
            return base.Channel.testServiceAsync(sec);
        }
        
        public string DatosClientes(int ptipo_convenio, string sec, string rutayarchivo) {
            return base.Channel.DatosClientes(ptipo_convenio, sec, rutayarchivo);
        }
        
        public System.Threading.Tasks.Task<string> DatosClientesAsync(int ptipo_convenio, string sec, string rutayarchivo) {
            return base.Channel.DatosClientesAsync(ptipo_convenio, sec, rutayarchivo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnpactoCA.WSTarjeta.ArchivoClientesResponse EnpactoCA.WSTarjeta.WSTarjetaSoap.ArchivoClientes(EnpactoCA.WSTarjeta.ArchivoClientesRequest request) {
            return base.Channel.ArchivoClientes(request);
        }
        
        public EnpactoCA.WSTarjeta.StreamReader ArchivoClientes(int ptipo_convenio, string sec, string rutayarchivo, ref string perror) {
            EnpactoCA.WSTarjeta.ArchivoClientesRequest inValue = new EnpactoCA.WSTarjeta.ArchivoClientesRequest();
            inValue.ptipo_convenio = ptipo_convenio;
            inValue.sec = sec;
            inValue.rutayarchivo = rutayarchivo;
            inValue.perror = perror;
            EnpactoCA.WSTarjeta.ArchivoClientesResponse retVal = ((EnpactoCA.WSTarjeta.WSTarjetaSoap)(this)).ArchivoClientes(inValue);
            perror = retVal.perror;
            return retVal.ArchivoClientesResult;
        }
        
        public System.Threading.Tasks.Task<EnpactoCA.WSTarjeta.ArchivoClientesResponse> ArchivoClientesAsync(EnpactoCA.WSTarjeta.ArchivoClientesRequest request) {
            return base.Channel.ArchivoClientesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnpactoCA.WSTarjeta.CargarMovimientosResponse EnpactoCA.WSTarjeta.WSTarjetaSoap.CargarMovimientos(EnpactoCA.WSTarjeta.CargarMovimientosRequest request) {
            return base.Channel.CargarMovimientos(request);
        }
        
        public long CargarMovimientos(int ptipo_convenio, string sec, string[] data, System.DateTime fecha, ref string perror) {
            EnpactoCA.WSTarjeta.CargarMovimientosRequest inValue = new EnpactoCA.WSTarjeta.CargarMovimientosRequest();
            inValue.ptipo_convenio = ptipo_convenio;
            inValue.sec = sec;
            inValue.data = data;
            inValue.fecha = fecha;
            inValue.perror = perror;
            EnpactoCA.WSTarjeta.CargarMovimientosResponse retVal = ((EnpactoCA.WSTarjeta.WSTarjetaSoap)(this)).CargarMovimientos(inValue);
            perror = retVal.perror;
            return retVal.CargarMovimientosResult;
        }
        
        public System.Threading.Tasks.Task<EnpactoCA.WSTarjeta.CargarMovimientosResponse> CargarMovimientosAsync(EnpactoCA.WSTarjeta.CargarMovimientosRequest request) {
            return base.Channel.CargarMovimientosAsync(request);
        }
    }
}
