//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACHTransactionPaymentWindowService.xpinnWSPayment {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentACH", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PaymentACH : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IDField;
        
        private ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentTypeEnum TypeField;
        
        private decimal AmountField;
        
        private decimal VATAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNumber1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNumber2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNumber3Field;
        
        private ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentStatusEnum StatusField;
        
        private bool ConfirmedGETField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        private int TypeProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrazabilityCodeField;
        
        private int TransactionCycleField;
        
        private System.DateTime SolicitedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentifierField;
        
        private long Cod_personaField;
        
        private long Cod_opeField;
        
        private System.DateTime Fecha_CreacionField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentTypeEnum Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal VATAmount {
            get {
                return this.VATAmountField;
            }
            set {
                if ((this.VATAmountField.Equals(value) != true)) {
                    this.VATAmountField = value;
                    this.RaisePropertyChanged("VATAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PaymentID {
            get {
                return this.PaymentIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentIDField, value) != true)) {
                    this.PaymentIDField = value;
                    this.RaisePropertyChanged("PaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PaymentDescription {
            get {
                return this.PaymentDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentDescriptionField, value) != true)) {
                    this.PaymentDescriptionField = value;
                    this.RaisePropertyChanged("PaymentDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ServiceCode {
            get {
                return this.ServiceCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceCodeField, value) != true)) {
                    this.ServiceCodeField = value;
                    this.RaisePropertyChanged("ServiceCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ReferenceNumber1 {
            get {
                return this.ReferenceNumber1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumber1Field, value) != true)) {
                    this.ReferenceNumber1Field = value;
                    this.RaisePropertyChanged("ReferenceNumber1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string ReferenceNumber2 {
            get {
                return this.ReferenceNumber2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumber2Field, value) != true)) {
                    this.ReferenceNumber2Field = value;
                    this.RaisePropertyChanged("ReferenceNumber2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ReferenceNumber3 {
            get {
                return this.ReferenceNumber3Field;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumber3Field, value) != true)) {
                    this.ReferenceNumber3Field = value;
                    this.RaisePropertyChanged("ReferenceNumber3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentStatusEnum Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public bool ConfirmedGET {
            get {
                return this.ConfirmedGETField;
            }
            set {
                if ((this.ConfirmedGETField.Equals(value) != true)) {
                    this.ConfirmedGETField = value;
                    this.RaisePropertyChanged("ConfirmedGET");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string BankCode {
            get {
                return this.BankCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BankCodeField, value) != true)) {
                    this.BankCodeField = value;
                    this.RaisePropertyChanged("BankCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public int TypeProduct {
            get {
                return this.TypeProductField;
            }
            set {
                if ((this.TypeProductField.Equals(value) != true)) {
                    this.TypeProductField = value;
                    this.RaisePropertyChanged("TypeProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string NumberProduct {
            get {
                return this.NumberProductField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberProductField, value) != true)) {
                    this.NumberProductField = value;
                    this.RaisePropertyChanged("NumberProduct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string TrazabilityCode {
            get {
                return this.TrazabilityCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TrazabilityCodeField, value) != true)) {
                    this.TrazabilityCodeField = value;
                    this.RaisePropertyChanged("TrazabilityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=18)]
        public int TransactionCycle {
            get {
                return this.TransactionCycleField;
            }
            set {
                if ((this.TransactionCycleField.Equals(value) != true)) {
                    this.TransactionCycleField = value;
                    this.RaisePropertyChanged("TransactionCycle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.DateTime SolicitedDate {
            get {
                return this.SolicitedDateField;
            }
            set {
                if ((this.SolicitedDateField.Equals(value) != true)) {
                    this.SolicitedDateField = value;
                    this.RaisePropertyChanged("SolicitedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentifierField, value) != true)) {
                    this.IdentifierField = value;
                    this.RaisePropertyChanged("Identifier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public long Cod_persona {
            get {
                return this.Cod_personaField;
            }
            set {
                if ((this.Cod_personaField.Equals(value) != true)) {
                    this.Cod_personaField = value;
                    this.RaisePropertyChanged("Cod_persona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public long Cod_ope {
            get {
                return this.Cod_opeField;
            }
            set {
                if ((this.Cod_opeField.Equals(value) != true)) {
                    this.Cod_opeField = value;
                    this.RaisePropertyChanged("Cod_ope");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=23)]
        public System.DateTime Fecha_Creacion {
            get {
                return this.Fecha_CreacionField;
            }
            set {
                if ((this.Fecha_CreacionField.Equals(value) != true)) {
                    this.Fecha_CreacionField = value;
                    this.RaisePropertyChanged("Fecha_Creacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentTypeEnum", Namespace="http://tempuri.org/")]
    public enum PaymentTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        normal = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        multicredit = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentStatusEnum", Namespace="http://tempuri.org/")]
    public enum PaymentStatusEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        pending = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        approved = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        rejected = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        failed = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentACHResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PaymentACHResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH PaymentObjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH> PaymentListField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH PaymentObj {
            get {
                return this.PaymentObjField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentObjField, value) != true)) {
                    this.PaymentObjField = value;
                    this.RaisePropertyChanged("PaymentObj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public System.Collections.Generic.List<ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH> PaymentList {
            get {
                return this.PaymentListField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentListField, value) != true)) {
                    this.PaymentListField = value;
                    this.RaisePropertyChanged("PaymentList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="xpinnWSPayment.WSPaymentSoap")]
    public interface WSPaymentSoap {
        
        // CODEGEN: Generating message contract since element name pPaymentRequest from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatePaymentTransaction", ReplyAction="*")]
        ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionResponse CreatePaymentTransaction(ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatePaymentTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionResponse> CreatePaymentTransactionAsync(ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionRequest request);
        
        // CODEGEN: Generating message contract since element name pPaymentRequest from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePaymentTransaction", ReplyAction="*")]
        ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionResponse UpdatePaymentTransaction(ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePaymentTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionResponse> UpdatePaymentTransactionAsync(ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionRequest request);
        
        // CODEGEN: Generating message contract since element name pPaymentFilter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultPaymentTransaction", ReplyAction="*")]
        ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionResponse ConsultPaymentTransaction(ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultPaymentTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionResponse> ConsultPaymentTransactionAsync(ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionRequest request);
        
        // CODEGEN: Generating message contract since element name pPaymentFilter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPaymentTransaction", ReplyAction="*")]
        ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionResponse ListPaymentTransaction(ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListPaymentTransaction", ReplyAction="*")]
        System.Threading.Tasks.Task<ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionResponse> ListPaymentTransactionAsync(ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePaymentTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePaymentTransaction", Namespace="http://tempuri.org/", Order=0)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionRequestBody Body;
        
        public CreatePaymentTransactionRequest() {
        }
        
        public CreatePaymentTransactionRequest(ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePaymentTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH pPaymentRequest;
        
        public CreatePaymentTransactionRequestBody() {
        }
        
        public CreatePaymentTransactionRequestBody(ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH pPaymentRequest) {
            this.pPaymentRequest = pPaymentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePaymentTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePaymentTransactionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionResponseBody Body;
        
        public CreatePaymentTransactionResponse() {
        }
        
        public CreatePaymentTransactionResponse(ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePaymentTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH CreatePaymentTransactionResult;
        
        public CreatePaymentTransactionResponseBody() {
        }
        
        public CreatePaymentTransactionResponseBody(ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH CreatePaymentTransactionResult) {
            this.CreatePaymentTransactionResult = CreatePaymentTransactionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePaymentTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePaymentTransaction", Namespace="http://tempuri.org/", Order=0)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionRequestBody Body;
        
        public UpdatePaymentTransactionRequest() {
        }
        
        public UpdatePaymentTransactionRequest(ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePaymentTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH pPaymentRequest;
        
        public UpdatePaymentTransactionRequestBody() {
        }
        
        public UpdatePaymentTransactionRequestBody(ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH pPaymentRequest) {
            this.pPaymentRequest = pPaymentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePaymentTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePaymentTransactionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionResponseBody Body;
        
        public UpdatePaymentTransactionResponse() {
        }
        
        public UpdatePaymentTransactionResponse(ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePaymentTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH UpdatePaymentTransactionResult;
        
        public UpdatePaymentTransactionResponseBody() {
        }
        
        public UpdatePaymentTransactionResponseBody(ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH UpdatePaymentTransactionResult) {
            this.UpdatePaymentTransactionResult = UpdatePaymentTransactionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultPaymentTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultPaymentTransaction", Namespace="http://tempuri.org/", Order=0)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionRequestBody Body;
        
        public ConsultPaymentTransactionRequest() {
        }
        
        public ConsultPaymentTransactionRequest(ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultPaymentTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pPaymentFilter;
        
        public ConsultPaymentTransactionRequestBody() {
        }
        
        public ConsultPaymentTransactionRequestBody(string pPaymentFilter) {
            this.pPaymentFilter = pPaymentFilter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultPaymentTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultPaymentTransactionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionResponseBody Body;
        
        public ConsultPaymentTransactionResponse() {
        }
        
        public ConsultPaymentTransactionResponse(ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultPaymentTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH ConsultPaymentTransactionResult;
        
        public ConsultPaymentTransactionResponseBody() {
        }
        
        public ConsultPaymentTransactionResponseBody(ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH ConsultPaymentTransactionResult) {
            this.ConsultPaymentTransactionResult = ConsultPaymentTransactionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListPaymentTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListPaymentTransaction", Namespace="http://tempuri.org/", Order=0)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionRequestBody Body;
        
        public ListPaymentTransactionRequest() {
        }
        
        public ListPaymentTransactionRequest(ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListPaymentTransactionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pPaymentFilter;
        
        public ListPaymentTransactionRequestBody() {
        }
        
        public ListPaymentTransactionRequestBody(string pPaymentFilter) {
            this.pPaymentFilter = pPaymentFilter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListPaymentTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListPaymentTransactionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionResponseBody Body;
        
        public ListPaymentTransactionResponse() {
        }
        
        public ListPaymentTransactionResponse(ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListPaymentTransactionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACHResult ListPaymentTransactionResult;
        
        public ListPaymentTransactionResponseBody() {
        }
        
        public ListPaymentTransactionResponseBody(ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACHResult ListPaymentTransactionResult) {
            this.ListPaymentTransactionResult = ListPaymentTransactionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSPaymentSoapChannel : ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSPaymentSoapClient : System.ServiceModel.ClientBase<ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap>, ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap {
        
        public WSPaymentSoapClient() {
        }
        
        public WSPaymentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSPaymentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPaymentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSPaymentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionResponse ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap.CreatePaymentTransaction(ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionRequest request) {
            return base.Channel.CreatePaymentTransaction(request);
        }
        
        public ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH CreatePaymentTransaction(ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH pPaymentRequest) {
            ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionRequest inValue = new ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionRequest();
            inValue.Body = new ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionRequestBody();
            inValue.Body.pPaymentRequest = pPaymentRequest;
            ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionResponse retVal = ((ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap)(this)).CreatePaymentTransaction(inValue);
            return retVal.Body.CreatePaymentTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionResponse> ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap.CreatePaymentTransactionAsync(ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionRequest request) {
            return base.Channel.CreatePaymentTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionResponse> CreatePaymentTransactionAsync(ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH pPaymentRequest) {
            ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionRequest inValue = new ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionRequest();
            inValue.Body = new ACHTransactionPaymentWindowService.xpinnWSPayment.CreatePaymentTransactionRequestBody();
            inValue.Body.pPaymentRequest = pPaymentRequest;
            return ((ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap)(this)).CreatePaymentTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionResponse ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap.UpdatePaymentTransaction(ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionRequest request) {
            return base.Channel.UpdatePaymentTransaction(request);
        }
        
        public ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH UpdatePaymentTransaction(ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH pPaymentRequest) {
            ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionRequest inValue = new ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionRequest();
            inValue.Body = new ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionRequestBody();
            inValue.Body.pPaymentRequest = pPaymentRequest;
            ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionResponse retVal = ((ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap)(this)).UpdatePaymentTransaction(inValue);
            return retVal.Body.UpdatePaymentTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionResponse> ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap.UpdatePaymentTransactionAsync(ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionRequest request) {
            return base.Channel.UpdatePaymentTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionResponse> UpdatePaymentTransactionAsync(ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH pPaymentRequest) {
            ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionRequest inValue = new ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionRequest();
            inValue.Body = new ACHTransactionPaymentWindowService.xpinnWSPayment.UpdatePaymentTransactionRequestBody();
            inValue.Body.pPaymentRequest = pPaymentRequest;
            return ((ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap)(this)).UpdatePaymentTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionResponse ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap.ConsultPaymentTransaction(ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionRequest request) {
            return base.Channel.ConsultPaymentTransaction(request);
        }
        
        public ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACH ConsultPaymentTransaction(string pPaymentFilter) {
            ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionRequest inValue = new ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionRequest();
            inValue.Body = new ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionRequestBody();
            inValue.Body.pPaymentFilter = pPaymentFilter;
            ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionResponse retVal = ((ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap)(this)).ConsultPaymentTransaction(inValue);
            return retVal.Body.ConsultPaymentTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionResponse> ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap.ConsultPaymentTransactionAsync(ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionRequest request) {
            return base.Channel.ConsultPaymentTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionResponse> ConsultPaymentTransactionAsync(string pPaymentFilter) {
            ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionRequest inValue = new ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionRequest();
            inValue.Body = new ACHTransactionPaymentWindowService.xpinnWSPayment.ConsultPaymentTransactionRequestBody();
            inValue.Body.pPaymentFilter = pPaymentFilter;
            return ((ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap)(this)).ConsultPaymentTransactionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionResponse ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap.ListPaymentTransaction(ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionRequest request) {
            return base.Channel.ListPaymentTransaction(request);
        }
        
        public ACHTransactionPaymentWindowService.xpinnWSPayment.PaymentACHResult ListPaymentTransaction(string pPaymentFilter) {
            ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionRequest inValue = new ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionRequest();
            inValue.Body = new ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionRequestBody();
            inValue.Body.pPaymentFilter = pPaymentFilter;
            ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionResponse retVal = ((ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap)(this)).ListPaymentTransaction(inValue);
            return retVal.Body.ListPaymentTransactionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionResponse> ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap.ListPaymentTransactionAsync(ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionRequest request) {
            return base.Channel.ListPaymentTransactionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionResponse> ListPaymentTransactionAsync(string pPaymentFilter) {
            ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionRequest inValue = new ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionRequest();
            inValue.Body = new ACHTransactionPaymentWindowService.xpinnWSPayment.ListPaymentTransactionRequestBody();
            inValue.Body.pPaymentFilter = pPaymentFilter;
            return ((ACHTransactionPaymentWindowService.xpinnWSPayment.WSPaymentSoap)(this)).ListPaymentTransactionAsync(inValue);
        }
    }
}
